# Generated by Django 5.0.6 on 2024-07-03 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_customuser_is_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraconfig',
            name='camera1_url',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='cameraconfig',
            name='camera2_url',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='cameraconfig',
            name='camera3_url',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='carplates',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
