# Generated by Django 5.0.6 on 2024-07-03 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_cameraconfig_camera1_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraconfig',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
