# Generated by Django 5.0.6 on 2024-07-03 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_cameraconfig_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='camera_config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.cameraconfig'),
        ),
        migrations.AlterField(
            model_name='cameraconfig',
            name='camera1_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cameraconfig',
            name='camera2_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cameraconfig',
            name='camera3_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
