# Generated by Django 5.0.6 on 2024-07-03 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_cameraconfig_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraconfig',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
